linters-settings:
    dupl:
        threshold: 100
        errcheck:
            check-type-assertions: true
    funlen:
        lines: 80
        statements: 60
    goconst:
        min-len: 2
        min-occurrences: 2
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - dupImport # https://github.com/go-critic/go-critic/issues/845
            - ifElseChain
            - octalLiteral
            - whyNoLint
            - wrapperFunc
    gocyclo:
        min-complexity: 20
    goimports:
        local-prefixes: github.com/wuhuizuo/sqlm
    revive:
        ignore-generated-header: true
        severity: warning
    gomnd:
        settings:
            mnd:
                checks:
                    - argument
                    - case
                    - condition
                    - return
    govet:
        check-shadowing: true
        settings:
            printf:
                funcs:
    lll:
        line-length: 120
    maligned:
        suggest-new: true
    misspell:
        locale: US

linters:
    # please, do not use `enable-all`: it's deprecated and will be removed soon.
    # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - funlen
        - gochecknoinits
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - revive
        - gomnd
        - goprintffuncname
        - gosimple
        - govet
        - ineffassign
        - lll
        - misspell
        - nakedret
        - rowserrcheck
        - exportloopref
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace

    # don't enable:
    # - gochecknoglobals
    # - gocognit
    # - godox
    # - maligned
    # - prealloc
    # - gosec

issues:
    # Excluding configuration per-path, per-linter, per-text and per-source
    exclude-rules:
        - path: _test\.go
          linters:
              - gomnd
              - dupl
              - exportloopref
              - funlen
